# SwiftLint의 기본 규칙을 따르면서, 일부 규칙은 비활성화합니다.
included:
  - Projects

excluded:
  - Projects/**/Project.swift

disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - function_parameter_count
  - type_body_length
  - file_length
  - large_tuple
  - discouraged_direct_init
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicit_return
  - implicitly_unwrapped_optional
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - redundant_self_in_closure
  - redundant_type_annotation
  - sorted_imports
  - toggle_bool
  - trailing_closure
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces


# 폴더명의 첫 글자가 대문자인 경우를 허용합니다.
identifier_name:
  excluded:
    - App
    - Data
    - Domain
    - Presentation
